### ISSUE TITLE
Uncaught Error: Key <field0.field1> must not contain '.'

### ISSUE THREAD

**Issue by ramezrafla** [ramezrafla/meteor-oplog-deepdiff#1]
This error is triggered by minimongo in validation.js

It seems minimongo batches some requests or augments them, so we get our $set query from the server `{"field0.field1":undefined}` in addition to the whole doc, and then minimongo is trying to replace the doc with one that has this $set query.

As minimongo expected top-level fields in updates, it was not an issue before. Now we have to dig deeper and see where the batching of queries takes place and prevent them from merging.

**Comment by ramezrafla** [comment]
Seems related to UI latency compensation (editing the DB almost at the same time as data is being pushed down)

**Comment by ramezrafla** [comment]
Fixed in latest commit 6e63a3f..4d42c85
However, it requires a hack in `ddp-client/livedata-connection.js` to export internal variable `Connection`. We simply added
```DDP.Connection = Connection```

Will communicate with Meteor team about this as this package is not functional without this hack.

**Comment by mitar** [comment]
You could also escape that. Maybe do some encoding or escaping.

**Comment by mitar** [comment]
You could get `Connection` using `Object.getPrototypeOf(Meteor.connection).constructor`, no?
